import { Inter } from 'next/font/google'
import CssBaseline from '@mui/material/CssBaseline'
import Navbar from '../components/layout/Navbar'
import { DataProvider } from '@/context/dataContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Enrollment Deep Dive',
  description: 'Generated by create next app',
  robots: {
    index: false,
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel='icon' href='/images/favicon.ico'/>
      </head>
      <CssBaseline />
      <DataProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </DataProvider>
    </html>
  )
}
